### PR TITLE
mix format

### PR DESCRIPTION
**Pull request by bradhanks**
I ran "mix format" and it changes the formatting of 109 files. so maybe better to start that change from the source :)

### CODE REVIEW

**Comment by RobertDober** [comment]
I see value in this, especially for collaboration, but I'd prefer to wait for a new maintainer to make these decisions

**Comment by bradhanks** [comment]
yeah i just submitted it as a placeholder.

**Comment by amit-chaudhari1** [comment]
The number of files affected is big. 

Let me revisit this after getting a bit more comfortable with the code. I intend to merge this.

**Comment by bradhanks** [comment]
> The number of files affected is big.
> 
> Let me revisit this after getting a bit more comfortable with the code. I intend to merge this.

yes it saw that. I wasn't sure if it was bc formatting styles had really changed, or existing suntax was unconventional or what

**Comment by RobertDober** [comment]
> yes it saw that. I wasn't sure if it was bc formatting styles had really changed, or existing suntax was 
> unconventional or what

as I was working alone for quite a period of time, I did only apply my own style which is quite unconventional, too bad one is so egostic,  sorry I left a little technical debt here

**Comment by bradhanks** [comment]
> > yes it saw that. I wasn't sure if it was bc formatting styles had really changed, or existing suntax was
> > unconventional or what
> 
> as I was working alone for quite a period of time, I did only apply my own style which is quite unconventional, too bad one is so egostic, sorry I left a little technical debt here

A little whitespace never hurt anyone. It's a pretty adjustment when we feel good about it :)

**Comment by bradhanks** [comment]
> > yes it saw that. I wasn't sure if it was bc formatting styles had really changed, or existing suntax was
> > unconventional or what
> 
> as I was working alone for quite a period of time, I did only apply my own style which is quite unconventional, too bad one is so egostic, sorry I left a little technical debt here

I don't know what this says about me but I do have the time and ambition enough to go through and verify that all that is changing in whitespace if you want to plug me in. :)

**Comment by amit-chaudhari1** [comment]
> I don't know what this says about me but I do have the time and ambition enough to go through and verify that all that is changing in whitespace if you want to plug me in.

I don't want to subject you to that, I do have this on my mind. I was looking around to see if there was a more definite widespread style guide we could adopt. 
eg: https://github.com/christopheradams/elixir_style_guide

regardless, I appreciate it.

**Comment by bradhanks** [comment]
I removed everything except the one format file

**Comment by RobertDober** [comment]
@amit-chaudhari1 courageous move :clap: will help a lot for collaboration

**Pull request merged**
