### PR TITLE
added SPDX information

### PR DESCRIPTION
**Pull request by RobertDober**
I like standardisation and formalisation, however maybe there are drawbacks or political battles I am not aware of.

What do you think about SPDX and should we try to comply?

### CODE REVIEW

**Comment by pragdave** [comment]
I had never heard of it until now.

I'm OK with adding it, but can it go at the end of the files, and not be the first line?

**Comment by RobertDober** [comment]
consider it done  

I can also keep the PR open for some while if you prefer.

**Comment by pragdave** [comment]
nah—go for it :)

Thanks

**Comment by RobertDober** [comment]
It seems there is a typo in your name in theconfiguration of github
notification, it reads "Dave Thoms"

--
Non datemi consigli che so sbagliare da solo
(Giuseppe Di Stefano)

**Comment by pragdave** [comment]
That's my new cool name: flickr, tumblr, thoms.

OK, it's a typo. Thanks

**Comment by RobertDober** [comment]
I almost fell for it, well done

--
Non datemi consigli che so sbagliare da solo
(Giuseppe Di Stefano)

**Pull request merged**
