### PR TITLE
Fix warning in Elixir 1.2

### PR DESCRIPTION
**Pull request by MSch**
Please release a new version to hex.pm after merging this, we're trying to get all our dependencies ready for 1.2. Thanks!

### CODE REVIEW

**Comment by RobertDober** [comment]
Ty very much

**Comment by RobertDober** [comment]
@pragdave If you can find the time for the release that would be great. Thanx in advance

**Comment by pragdave** [comment]
I’m getting compilation errors:

[~/P/earmark] mix test
lib/earmark/cli.ex:1: warning: redefining module Earmark.CLI
lib/earmark/context.ex:1: warning: redefining module Earmark.Options
lib/earmark.ex:1: warning: redefining module Earmark
lib/earmark/context.ex:22: warning: redefining module Earmark.Context
Compiled lib/earmark/cli.ex
Compiled lib/earmark/context.ex
lib/earmark/helpers.ex:1: warning: redefining module Earmark.Helpers
lib/earmark/block.ex:1: warning: redefining module Earmark.Block

== Compilation error on file lib/earmark/block.ex ==
** (CompileError) lib/earmark/block.ex:3: cannot import
Earmark.Helpers.pending_inli
ne_code/1 because it doesn't exist
    (elixir) src/elixir_import.erl:68: :elixir_import.calculate/6
    (elixir) src/elixir_import.erl:18:
:elixir_import.import/4[~/P/earmark] elixir --version
Erlang/OTP 18 [erts-7.1] [source] [64-bit] [smp:4:4]
[async-threads:10] [hipe] [kern
el-poll:false] [dtrace]

Elixir 1.2.0-rc.1 (211a129)

Dave
​

**Comment by RobertDober** [comment]
Strange, all's green locally and on Travis for the master branch.
I'll disable Travis for the development branch.
The error you are having had occurred in some older commits that should not be on master, probably my error. Could you try again please.
Commit should be 55828d1131581554712849bbacd82a88568ba66c

**Comment by pragdave** [comment]
I blew way my local copy and tried again. All working now.

Pushed to hex.

**Comment by RobertDober** [comment]
Thx a lot and sorry for the hickup that should not have happened...

**Pull request merged**
