### PR TITLE
Add unicode modifier to pure link regex

### PR DESCRIPTION
**Pull request by StephaneRob**

### CODE REVIEW

**Comment by StephaneRob** [comment]
Fix #243

**Comment by RobertDober** [comment]
Great.
I merge this and will add tests and check for other regexen before the release.

As you are using master and not the released version that should be good for you.

Thank you for your help.

**Comment by StephaneRob** [comment]
Thanks @RobertDober, I had a look on other regexen but didn't notice anything.
Tell me if I can help.

**Comment by RobertDober** [comment]
If you have time to add some acceptance or regression tests for the issue it would be great, but no stress on this.

Thx again.

**Pull request merged**
