### PR TITLE
deprecation warning for unmatched quotes implemented

### PR DESCRIPTION
**Pull request by RobertDober**

### CODE REVIEW

**Comment by RobertDober** [comment]
@pragdave 
this merge would allow for the release of 1.2, if you agree with the choices I have made, these being...

* Elixir < 1.4, not suppotyed anymore
* Errors Warnings are not transported all through the callstack from scanning to parsing and rendering, but I created a _Messages_ `Agent` that allows for all processed to add state in a Fire & Forget manner. This made the (still quite fat) function signatures quite a bit leaner. On the downside it is _theoretically_ possible that errors/warnings are missing (in case of a timeout).
* I implemented issue #131 because I feel it has some real value and kramdown does it too ;)
* During the necessary changes to the README I decided to add some doctests to the README the result being less pretty than I hoped for, but that is something we could undo easily even after release.

If any of these initiatives does not meet your approval I can undo it (though I was a little bit too eager merging into master, sorry about that)

**Comment by pragdave** [comment]
I think this is all fantastic. Thank you.

Let me know when you're reading for me to release it.

**Comment by RobertDober** [comment]
@pragdave thank you for your support I will let you know ASAP

**Comment by RobertDober** [comment]
@pragdave I guess you did not get a notif when I modified the comment above. If you're busy there is no rush of course, but master is ready for release of 1.2.

**Comment by pragdave** [comment]
I may have just missed it.

1.2 has been pushed.

Thank you again for all your hard work.

**Pull request merged**
