### PR TITLE
I106 plugins

### PR DESCRIPTION
**Pull request by RobertDober**
@pragdave as  I am progressing on 1.1 maybe I prefer to release 1.0.3 now, before I merge the two PRs (this one, and the one for issue #62). So we have a nice and easy 1.0.3, just with bugfixes (#95, #96, #99 and #103), especially as #99 and #103 crash Earmark. What do you think?

### CODE REVIEW

**Comment by pragdave** [comment]
Sounds like a plan. Let me know when you want a release.

What a lot of work you've done.

Thank you.


Dave

**Comment by RobertDober** [comment]
Thank you Dave, just taking advantage of my unemployment ;)
Release now would be great.

**Comment by pragdave** [comment]
'tis done.

**Comment by RobertDober** [comment]
Great Dave, thank you

**Pull request merged**
