### PR TITLE
Simplify Transform module

### PR DESCRIPTION
**Pull request by eksperimental**

### CODE REVIEW

**Comment by RobertDober** [comment]
Thank you, normally I could merge this easily but right now we will have conflicts with #337, I will certainly incoperate this later.

**Comment by RobertDober** [comment]
Now I am confused, do not follow this anymore :bliush:

**Comment by eksperimental** [comment]
> Now I am confused, do not follow this anymore :bliush:

That' s OK. I can review the new Transform module and reapply these changes if needed. No worries.

**Comment by eksperimental** [comment]
I see you have done it. Good!

**Pull request merged**
