### PR TITLE
checking availbity of 1.2.[45] on Travis

### PR DESCRIPTION
**Pull request by RobertDober**

### CODE REVIEW

**Comment by RobertDober** [comment]
well it does :)
@pragdave do you think the delat to 0.2.1 would justify a release?

**Comment by pragdave** [comment]
Are there any functional changes?

**Comment by RobertDober** [comment]
@pragdave hmm only two
* the correct handling of html void tags, well those which make sense in markdown at least. #61
* language specific fance blocks (for CSS synatx highlighting) #60

**Comment by pragdave** [comment]
Cool. It's up to you, but a release probably wouldn't be a bad thing.

**Pull request merged**
