### PR TITLE
Makes use of Map instead of Dict

### PR DESCRIPTION
**Pull request by riacataquian**
Removes HashDict and Dict data types in favor of Map.
http://elixir-lang.org/docs/stable/elixir/HashDict.html

### CODE REVIEW

**Comment by ericmj** [comment]
Should bump elixir requirement to 1.2.0 also.

**Comment by riacataquian** [comment]
Oh yes @ericmj. I forgot. :)

**Comment by RobertDober** [comment]
Great job if you could also remove the failing chex for Elixir versions < 1.2 that would be perfect.
If you do not have the time I can do it after the merge but I hate to get the red Travis CI label on the main branch...

**Comment by riacataquian** [comment]
I would love to @RobertDober! But.. I don't understand why it fails. If you could give me some inputs, I'd  also be happy to make it pass.

**Comment by ericmj** [comment]
@riacataquian You need to remove the tests for elixir 1.0 and 1.1 in .travis.yml https://github.com/pragdave/earmark/pull/64/commits/fdbe642c18924a118cd5fecf0306c85fcf4a407c#diff-354f30a63fb0907d4ad57269548329e3R10 since elixir 1.2+ is now required.

**Comment by riacataquian** [comment]
TIL. Thanks @ericmj!

**Comment by RobertDober** [comment]
<3 at both of you

**Comment by RobertDober** [comment]
BTW I'll check if 1.2.4 & 1.2.5 are ready on Travis

**Pull request merged**
