### PR TITLE
Fix Elixir 1.4 warnings

### PR DESCRIPTION
**Pull request by milmazz**
Fix some Elixir 1.4 warnings

### CODE REVIEW

**Comment by RobertDober** [comment]
Thank you. I will need to merge #73 first though to see what will remain. Seems this is fixing more or less the same warnings.

**Comment by whatyouhide** [comment]
#73 should fix all warnings that 1.4 prints as of now. @RobertDober, if you find any warnings I didn't cover, you can just ping me so that we fix all in one PR. :)

**Comment by milmazz** [comment]
@RobertDober I'll close this in favor of #73

@whatyouhide Great job!, you should also fix some warnings in `test/support/helpers.ex`, is the only thing missing in your PR. Thanks.

**Comment by RobertDober** [comment]
no need to close it ;) after merge the diff will update, right?

**Comment by whatyouhide** [comment]
Updated #73 with fixes for the warnings in `test/support/helpers.ex`, thanks for the pointer @milmazz!

**Comment by RobertDober** [comment]
@whatyouhide so there is no need for #74 any more thank you both - Elixir1.4 w/o Italians, impossible ;)

**Pull request closed without merging**
