### PR TITLE
Fix typo in a doc

### PR DESCRIPTION
**Pull request by niku**

### CODE REVIEW

**Comment by RobertDober** [comment]
Thank you for your PR, actually this is not a typo, I use _iff_ in this sense:  https://www.merriam-webster.com/dictionary/iff

**Comment by niku** [comment]
Oh, thank you.
I haven't known that word 😭 

Thank you for your fast and kind answer.
I'll close the PR.

**Comment by RobertDober** [comment]
I have not closed the PR because I thought that maybe _iff_ is not such a good idea.

One one hand it is a precise way, but if unknown by many, maybe replacing _iff_ by a clearer _if and only if_, or _exactly if_ might be a good idea, 

Using English maybe we should express ourseleves in a simpler way, what do you think?

**Comment by niku** [comment]
I agree with your thoughts.

My opinion is using _if and only if_ makes the document be better.

It is a little bit verbose for some people.
But it is easier to grab what the words mean for non-native English reader like me.

**Comment by RobertDober** [comment]
Thank you for your feedback, here we go https://github.com/pragdave/earmark/commit/e65fcf67345c84c23d237c732e5c174246662c68

**Pull request closed without merging**
