### PR TITLE
~R is deprecated

### PR DESCRIPTION
**Pull request by bradhanks**

### CODE REVIEW

**Comment by RobertDober** [comment]
Ty for your PR, as you can see this does not seem to work

**Comment by bradhanks** [comment]
we are back in business. :)

I really enjoyed your course, btw. It was excellent advice to physically follow along and type everything out as the lessons progressed. I've actually continued that with doing some exercises with pen and paper to see if I really know it or if I'm just being prompted.

**Comment by RobertDober** [comment]
What course are you talking about?

I need to reflect a little bit about all the changes, you might not know that I have stepped down as a maintainer of Earmark so I's rather not spend too much time with it.

We should definitely take care of the deprecation warning, but the rest?

**Comment by RobertDober** [comment]
BTW would you be interested to maintain Earmark?

**Comment by bradhanks** [comment]
I don't really know I'm qualified but in theory I'm not opposed to it.

**Comment by RobertDober** [comment]
Hmm most feature changes would probably go to the parser of which I still (try to) take care and new features concering the transformation into html I have not seen for quite some time but I do not want to talk you into it ;)

**Comment by bradhanks** [comment]
> Hmm most feature changes would probably go to the parser of which I still (try to) take care and new features concering the transformation into html I have not seen for quite some time but I do not want to talk you into it ;)

No I'm happy to help as long as you know I'm probably going to be hesistant to be involved in anything that might break something. I have no problem manning the desk :)

**Comment by RobertDober** [comment]
Then I suggest the following:
- I will ask Dave to give you full commit rights
- I will of course help if I can and maybe do releases for now but that is up to Dave and you
what do you think?

**Comment by amit-chaudhari1** [comment]
Sorry for barging in on the conversation,

@RobertDober I'd also like to be considered for being a maintainer.
if @bradhanks and @RobertDober allow me to take over and do not have any plans about where we should take this forward,
I'm describing my plans [here](https://github.com/pragdave/earmark/issues/477).

I've picked up Elixir for about 10 months now gotten comfortable around the ecosystem, and I think it is my time to give back to this community.

If @bradhanks is okay with it. Could you please consider me for maintaining this library?

**Comment by bradhanks** [comment]
> Then I suggest the following:
> 
> * I will ask Dave to give you full commit rights
> * I will of course help if I can and maybe do releases for now but that is up to Dave and you
>   what do you think?

Sign me up :)

**Comment by bradhanks** [comment]
> What course are you talking about?
> 
> I need to reflect a little bit about all the changes, you might not know that I have stepped down as a maintainer of Earmark so I's rather not spend too much time with it.
> 
> We should definitely take care of the deprecation warning, but the rest?

Sorry I'm really green. Dave has a course. I didn't even look at the username. I just assumed it was him because it is in a repo named after him.

**Comment by amit-chaudhari1** [comment]
Looks Good.

There's
- Readability refactors.
- map_join refactors
- ~R deprecation refactor

Ref: [ `~R` is deprecated in favour of `~r` ](https://elixirforum.com/t/elixir-v1-16-0-released/60530)
> [Kernel] ~R/.../ is deprecated in favor of ~r/.../. This is because ~R/.../ still allowed escape codes, which did not fit the definition of uppercase sigils

**Pull request merged**
